/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BlogWebsite;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAValidPOrt() {
        assertNotNull(App.getHerokuAssignedPort(), "app should have a port number");
    }
}
